import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import ThemeProviderLayour from "./components/themeLayout/themeLayout";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <ThemeProviderLayour>
        <body
          className={`${inter.className} dark:bg-slate-900 bg-stone-100 mx-3`}
        >
          {children}
        </body>
      </ThemeProviderLayour>
    </html>
  );
}
